# Generated by Django 6.0.4 on 2026-04-28 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title_course",
                    models.CharField(
                        help_text="Введите название курса", max_length=250, verbose_name="Наименование курса"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью курса",
                        null=True,
                        upload_to="courses/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "gif"])],
                        verbose_name="Превью курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Введите подробное описание курса", verbose_name="Описание курса"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если курс доступен для просмотра",
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца курса",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец (преподаватель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_section", models.CharField(max_length=200, verbose_name="Название раздела")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title_lesson",
                    models.CharField(
                        help_text="Введите название урока", max_length=250, verbose_name="Наименование урока"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите подробное описание урока", verbose_name="Описание урока"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью урока",
                        null=True,
                        upload_to="lessons/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "gif"])],
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Вставьте ссылку на видео", verbose_name="Ссылка на видео"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок урока")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца урока",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Выберите раздел курса, к которому относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.section",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
