# Generated by Django 6.0.4 on 2026-04-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField(verbose_name="Вопрос")),
                ("correct_answer", models.CharField(max_length=800, verbose_name="Правильный ответ")),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="materials.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_answer", models.CharField(max_length=800, verbose_name="Ответ студента")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Правильно?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="materials.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка теста",
                "verbose_name_plural": "Попытки тестов",
                "ordering": ["-created_at"],
            },
        ),
    ]
