# Generated by Django 6.0.4 on 2026-04-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_test_testattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядковый номер урока"),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядковый номер раздела"),
        ),
    ]
