# Generated by Django 6.0.4 on 2026-05-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_order_alter_section_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
